In [1]:
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
from matplotlib.pyplot import boxplot
import itertools
from scipy import stats
import sys
sys.path.insert(0,'../..')
from g4l.data import Sample
from g4l.tree import ContextTree
import g4l.display
import g4l.estimators.ctm as ctm

# load initial data
X = Sample('../example1/folha.txt', [0, 1, 2, 3, 4])
initial_tree = ContextTree(X, max_depth=4)

In [2]:
# Max tree depth used
max_depth = 4
# Alphabet
A = [0, 1, 2, 3, 4]
# Penalization constant required for BIC
c = 0.5

In [4]:
sample = g4l.data.Sample('../example1/folha.txt', A)
initial_tree = g4l.tree.ContextTree(sample, max_depth=max_depth, tree_initialization_method=g4l.tree.generation.incremental_strategy)

In [6]:
initial_tree.df

,node_idx,node,len_idx,node_freq,l,parent_idx,node_prob,lps,transition_sum_log_probs,final,flag
0,0,2,0,21830,1,None,0.223323,-14715.435172,-1.424897,0,0
1,1,1,1,21830,1,None,0.223323,-18794.382713,-8.296834,0,0
2,2,0,2,44111,1,None,0.451259,-62840.152905,-9.367255,0,0
3,3,3,3,7909,1,None,0.080910,-6671.568838,-9.670055,0,0
4,4,4,4,2070,1,None,0.021176,-1333.215732,-9.133726,0,0
...,...,...,...,...,...,...,...,...,...,...,...
228,228,3334,148,1,4,68,0.010309,0.000000,0.000000,0,0
229,229,3342,149,2,4,79,0.666667,-1.386294,-1.386294,0,0
230,230,0334,150,2,4,59,0.004525,-1.386294,-1.386294,0,0
231,231,4214,151,1,4,61,0.001656,0.000000,0.000000,0,0
232,232,3343,152,1,4,79,0.333333,0.000000,0.000000,0,0